# Generated by Django 4.1.1 on 2022-09-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_adminprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('WRITER', 'writer'), ('READER', 'reader')], max_length=50, verbose_name='Type'),
        ),
    ]
