# Generated by Django 4.1.1 on 2022-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_image_writerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerprofile',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='images/'),
        ),
    ]
