# Generated by Django 4.1.1 on 2022-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_writerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerprofile',
            name='image',
            field=models.ImageField(default='media/default_user.png', upload_to='images/'),
        ),
    ]
