# Generated by Django 4.1.1 on 2022-11-12 11:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_writerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
