# Generated by Django 4.1.1 on 2022-11-12 16:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nationality',
        ),
        migrations.AddField(
            model_name='readerprofile',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
