# Generated by Django 4.1.1 on 2022-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_delete_opinion_delete_politic_article_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('OPINION', 'opinion'), ('POLITICS', 'politics'), ('HEADLINES', 'headlines')], max_length=255, verbose_name='Type'),
        ),
    ]
